# Main k8s Setup
---
- name: Add Nginx-Ingress Helm-Chart repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  tags: [k8s, k8s-init, k8s-ingress, k8s-ingress-nginx]

- name: Deploy Nginx-Ingress
  kubernetes.core.helm:
    name: ingress-nginx
    state: present
    chart_version: '{{ k8s_nginx_helm_chart_version }}'
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    update_repo_cache: true
    wait: true
    values: '{{ k8s_nginx_helm_values | default({}) }}'
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
  tags: [k8s, k8s-init, k8s-ingress, k8s-ingress-nginx]
