# Main k8s Setup
---
- name: Add ArgoCD Helm-Chart repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm
  tags: [k8s, k8s-argo]

- name: Deploy ArgoCD
  kubernetes.core.helm:
    name: argo
    state: present
    chart_version: '{{ k8s_argocd_helm_chart_version }}'
    chart_ref: argo/argo-cd
    release_namespace: argo
    create_namespace: true
    update_repo_cache: true
    atomic: true
    wait: true
    values: '{{ k8s_argocd_helm_values | default({}) }}'
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
  tags: [k8s, k8s-argo]
