# K8s install longhorn

- name: Add Longhorn Helm-chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  tags: [k8s, k8-helm, k8s-longhorn]

- name: Deploy Longhorn
  kubernetes.core.helm:
    name: longhorn
    state: '{{ "present" if(k8s_longhorn_install) else "absent" }}'
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    chart_version: "{{ k8s_longhorn_chart_version }}"
    create_namespace: true
    update_repo_cache: true
    atomic: true
    wait: true
    values: "{{ k8s_longhorn_helm_values | default({}) }}"
    kubeconfig: "{{ k8s_kubeconfig | default('/etc/kubernetes/admin.conf') }}"
  tags: [k8s, k8-helm, k8s-longhorn]
