# Main InfluxDB Setup
---
- name: Install needed packages
  ansible.builtin.apt:
    name: python3-influxdb
    state: latest
  tags: [influxdb]

- name: Check if Docker is installed
  when: influx_use_docker | bool
  ansible.builtin.command: docker --version
  register: docker_valid
  ignore_errors: true
  changed_when: false
  tags: [influxdb]

- name: Run Docker install
  when: influx_use_docker | bool and docker_valid.failed | default(true)
  ansible.builtin.include_role:
    name: docker
  vars:
    docker_init_swarm: false
    docker_install_portainer: false
  tags: [influxdb]

- name: Install Influxdb
  when: influx_use_docker | bool
  ansible.builtin.include_tasks: install-influxdb-docker.yml
  tags: [influxdb]

- name: Install Influxdb
  when: influx_use_docker | bool == false
  ansible.builtin.include_tasks: install-influxdb.yml
  tags: [influxdb]

- name: Ensure handlers are notified now
  ansible.builtin.meta: flush_handlers
  tags: [influxdb]

# Broken right now because influx 2.x
# - name: Init Influxdb
#   ansible.builtin.include_tasks: init-influxdb.yml
#   tags: [influxdb]

- name: Create backup directory if it does not exist
  ansible.builtin.file:
    path: '{{ backup_dir }}'
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags: [influxdb]

- name: Copy backup script
  ansible.builtin.copy:
    src: '{{ influx_db_backup_script }}'
    dest: '{{ backup_dir }}/run_backup.sh'
    owner: root
    group: root
    mode: '0755'
  tags: [influxdb]

- name: Setup cron jobs
  ansible.builtin.include_tasks: shared/install-cron-jobs.yml
  vars:
    cron_jobs: '{{ influx_cron_jobs }}'
  tags: [influxdb, cron]
