# Main k8s Setup
---
- name: Add Grafana Helm-Chart repo
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts
  tags: [k8s, k8s-grafana-mimir, k8s-mimir]

- name: Deploy Grafana Mimir
  kubernetes.core.helm:
    name: mimir
    state: present
    chart_version: '{{ k8s_mimir_helm_chart_version }}'
    chart_ref: grafana/mimir-distributed
    release_namespace: mimir
    create_namespace: true
    update_repo_cache: true
    atomic: true
    wait: true
    values: '{{ k8s_mimir_helm_values | default({}) }}'
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
  tags: [k8s, k8s-grafana-mimir, k8s-mimir]
