stages:
  - schedule
  - test
  - prebuild
  - build
  - sec-scan
  - pages
  - distribute
  - deploy

variables:
  VARIANT: default

include:
  - project: hegerdes/templates
    file: /gitlab/ci/defaults.yml
  - project: hegerdes/templates
    file: /gitlab/ci/kaniko-build.yml

image-build-playbooks:
  extends: .build_template
  variables:
    BUILD_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  rules:
    - if: $CI_COMMIT_REF_NAME
    - if: $CI_COMMIT_TAG
