stages:
  - schedule
  - test
  - prebuild
  - build
  - sec-scan
  - pages
  - distribute
  - deploy

variables:
  VARIANT: default

include:
  - project: hegerdes/templates
    file: /gitlab/ci/defaults.yml
  - project: hegerdes/gitlab-actions
    file: .gitlab/ci/snippets.yml
  - project: hegerdes/gitlab-actions
    file: .gitlab/ci/rules.yml
  - component: $CI_SERVER_HOST/hegerdes/gitlab-actions/kaniko-build@main
    inputs:
      add_image_arch_postfix: true

KANIKO:build:
  tags: [$RUNNER]
  variables:
    # CONTAINER_BUILD_EXTRA_ARGS: --compressed-caching=false
    CONTAINER_BUILD_EXTRA_ARGS: --use-new-run
  parallel:
    matrix:
      - RUNNER: saas-linux-small-amd64
      - RUNNER: hegerdes-linux-arm64
