stages:
  - schedule
  - test
  - prebuild
  - build
  - package
  - sec-scan
  - pages
  - distribute
  - deploy

variables:
  VARIANT: default

include:
  - project: hegerdes/templates
    file: /gitlab/ci/defaults.yml
  - project: hegerdes/gitlab-actions
    file: .gitlab/ci/snippets.yml
  - project: hegerdes/gitlab-actions
    file: .gitlab/ci/rules.yml
  - component: $CI_SERVER_HOST/hegerdes/gitlab-actions/kaniko-build@main
    inputs:
      add_image_arch_postfix: true
  - component: gitlab.com/hegerdes/gitlab-actions/container-manifest-merge@main
    inputs:
      stage: package

KANIKO:build:
  tags: [$RUNNER]
  variables:
    CONTAINER_BUILD_EXTRA_ARGS: --snapshot-mode=redo --use-new-run --compressed-caching=false
    # CONTAINER_BUILD_EXTRA_ARGS: --compressed-caching=false --single-snapshot --use-new-run --snapshot-mode=redo
  parallel:
    matrix:
      - RUNNER: saas-linux-small-amd64
      - RUNNER: hegerdes-linux-arm64
