stages:
  - schedule
  - test
  - prebuild
  - build
  - sec-scan
  - pages
  - distribute
  - deploy

variables:
  VARIANT: default

include:
  - project: hegerdes/templates
    file: /gitlab/ci/defaults.yml
  - project: hegerdes/gitlab-actions
    file: .gitlab/ci/snippets.yml
  - project: hegerdes/gitlab-actions
    file: .gitlab/ci/rules.yml
  - component: $CI_SERVER_HOST/hegerdes/gitlab-actions/kaniko-build@main
    inputs:
      context: $CI_PROJECT_DIR/tests
      dockerfile: $CI_PROJECT_DIR/tests/Dockerfile
      add_image_arch_postfix: true

KANIKO:build:
  tags: [$RUNNER]
  # Multiple pushes may cause race condition. Retry twice
  retry: 2
  parallel:
    matrix:
      - RUNNER: saas-linux-small-amd64
      - RUNNER: hegerdes-linux-arm64
