# Main Playbook
- hosts: personal
  become: true
  gather_facts: true
  vars_files:
    - "{{ inventory_dir }}/secrets/vault.yml"

  roles:
    # - common
    # - docker
    # - promtail
    # - cloudflare-dns
    - docker-deploy
