# Deploy playbook

- hosts: k8s
  become: true
  gather_facts: true
  roles:
    - netlify-dns
    - k8s/common
  vars_files:
    - '{{ inventory_dir }}/secrets/vault.yml'

- hosts: k8s_master
  become: true
  gather_facts: true
  roles:
    - k8s/master
    # - k8s/metallb
    # - k8s/hetzner
    # - k8s/longhorn
    - k8s/certmanager
    - k8s/ingress-nginx
    # - k8s/ingress-traefik
    - k8s/monitoring
    - k8s/deploy
  vars_files:
    - '{{ inventory_dir }}/secrets/vault.yml'

- hosts: k8s_worker
  become: true
  gather_facts: true
  roles:
    - k8s/worker-join
  vars_files:
    - '{{ inventory_dir }}/secrets/vault.yml'

# - hosts: k8s_worker
#   become: true
#   gather_facts: true
#   roles:
#     - k8s/worker-leave

