# Deploy playbook

- hosts: k8s
  become: true
  gather_facts: true
  vars_files: ['{{ inventory_dir }}/secrets/vault.yml']
  roles:
    - netlify-dns
    - k8s/common
    # - k8s/upgrade

- hosts: k8s_master
  become: true
  gather_facts: true
  vars_files: ['{{ inventory_dir }}/secrets/vault.yml']
  roles:
    - k8s/master


- hosts: k8s_worker
  become: true
  gather_facts: true
  vars_files: ['{{ inventory_dir }}/secrets/vault.yml']
  roles:
    - k8s/worker-join

- hosts: k8s_master
  become: true
  gather_facts: true
  vars_files: ['{{ inventory_dir }}/secrets/vault.yml']
  roles:
    - k8s/hetzner
    - k8s/certmanager
    - k8s/metrics
    - k8s/monitoring
    - k8s/ingress-nginx
    # - k8s/ingress-traefik
    # - k8s/longhorn
    # - k8s/grafana-mimir
    # - k8s/metallb
    - k8s/argocd
    - k8s/deploy
    # - k8s/rancher


# - hosts: k8s_master
#   become: true
#   gather_facts: true
#   roles:
#     - k8s/grafana-mimir
#     - k8s/longhorn
#     # - k8s/metallb
#     - k8s/deploy
#     - k8s/argocd
#     # - k8s/rancher
#   vars_files:
#     - '{{ inventory_dir }}/secrets/vault.yml'

# # Leave
# - hosts: k8s_worker
#   become: true
#   gather_facts: true
#   roles:
#     - k8s/worker-leave

# - hosts: localhost
#   become: false
#   gather_facts: true
#   roles:
    # - k8s/metallb
    # - k8s/hetzner
    # - k8s/longhorn
    # - k8s/certmanager
    # - k8s/ingress-nginx
    # - k8s/ingress-traefik
    # - k8s/monitoring
    # - k8s/deploy
