# Deploy playbook

- name: DNS
  hosts: k8s
  become: false
  gather_facts: false
  roles:
    - cloudflare-dns

- name: K8s-Cluster-Preparation
  hosts: k8s
  become: true
  gather_facts: true
  roles:
    - k8s/common

- name: K8s-bootstrap
  hosts: k8s_control_plane
  become: true
  gather_facts: true
  roles:
    - k8s/control-plane
    - k8s/hcloud-autoscale-conf

- name: K8s-Worker-Join
  hosts: k8s_worker
  become: true
  gather_facts: true
  roles:
    - k8s/worker-join

- name: K8s-Deploy
  hosts: k8s_control_plane
  serial: 1
  become: true
  gather_facts: true
  roles:
    - k8s/argocd
    - k8s/deploy
# - k8s/hetzner
# - k8s/certmanager
# - k8s/ingress-nginx
# - k8s/ingress-kong
# - k8s/metrics
# - k8s/monitoring
# - k8s/ingress-traefik
# - k8s/longhorn
# - k8s/grafana-mimir
# - k8s/metallb
# - k8s/rancher

# # Upgrade
# - hosts: k8s
#   become: true
#   gather_facts: true
#   roles:
#     - k8s/etcd
#     - k8s/upgrade

# # Leave
# - hosts: k8s_worker
#   become: true
#   gather_facts: true
#   roles:
#     - k8s/worker-leave
