k8s_hetzner_api_key: none
k8s_hetzner_network_name_or_id: my-k8s-network
k8s_hetzner_csi_driver_install: true
k8s_hcloud_csi_version: v2.3.2

k8s_hetzner_ccm_install: true
k8s_hetzner_ccm_helm_repo: https://charts.hetzner.cloud
k8s_hetzner_ccm_helm_chart_version: '{{ null | default(omit) }}'
k8s_hetzner_ccm_helm_values: {}
# Example
# https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/chart/values.yaml
# k8s_hetzner_ccm_helm_values:
#   networking:
#     enabled: true
#     # If networking is enabled, clusterCIDR must match the PodCIDR subnet your cluster has been configured with.
#     # The default "10.244.0.0/16" assumes you're using Flannel with default configuration.
#     clusterCIDR: "10.244.0.0/16"

k8s_hetzner_lb_exporter_install: true
k8s_hetzner_lb_exporter_helm_repo: https://wacken89.github.io/hetzner-load-balancer-prometheus-exporter
k8s_hetzner_lb_exporter_helm_chart_version: '{{ null | default(omit) }}'
k8s_hetzner_lb_exporter_helm_values: {}
# Example
# https://github.com/wacken89/hetzner-load-balancer-prometheus-exporter/blob/master/deploy/helm-chart/values.yaml
# k8s_hetzner_lb_exporter_helm_values:
#   env:
#     # Set envs like in the kubernetes pod spec
#     - name: LOAD_BALANCER_IDS
#       value: "all"
#     - name: SCRAPE_INTERVAL
#       value: "60"
#     - name: ACCESS_TOKEN
#       value: ""
#     # Or set token via secret ref
#     # - name: ACCESS_TOKEN
#     #   valueFrom:
#     #     secretKeyRef:
#     #       key: token
#     #       name: hcloud
