k8s_hetzner_api_key: none
k8s_hetzner_network_name_or_id: my-k8s-network
k8s_hetzner_use_ccm_pvt_networks: true
k8s_hetzner_csi_driver_install: true
k8s_hetzner_ccm_install: true
k8s_hetzner_lb_install: true
k8s_hetzner_lb_exporter_helm_repo: https://wacken89.github.io/hetzner-load-balancer-prometheus-exporter
k8s_hetzner_lb_exporter_helm_chart_version: '{{ null | default(omit) }}'
k8s_hetzner_lb_exporter_helm_values: {}
k8s_hcloud_csi_version: v2.3.2
# # Example
# k8s_hetzner_lb_exporter_helm_values:
#   env:
#     # Set envs like in the kubernetes pod spec
#     - name: LOAD_BALANCER_IDS
#       value: "all"
#     - name: SCRAPE_INTERVAL
#       value: "60"
#     - name: ACCESS_TOKEN
#       value: ""
#     # Or set token via secret ref
#     # - name: ACCESS_TOKEN
#     #   valueFrom:
#     #     secretKeyRef:
#     #       key: token
#     #       name: hcloud
