---
##### general #####

# Timezone
common_time_zone: Europe/Berlin
common_hostname: none

# Install extra packages
common_extra_packages: []
common_delete_packages: []
# Floating ips
common_floating_ips: []

common_ssh_key_repo: '{{lookup("env", "SSH_KEY_REPO") | default("none", true)}}'
common_ssh_key_repo_branch: master
common_unattended_upgrades_state: present
common_selinux_mode: permissive             # can be: disabled,enforcing,permissive
common_selinux_policy: targeted
# List of key_paths
common_ssh_keys: []
common_ssh_key_dir: data/ssh_keys
common_default_network_device: ens10
# Example
# common_ssh_keys:
#   - filename: '{{ inventory_dir }}/key.pub'
#     state: present                # optional
#     user: root                    # optional
#     key_options: ''               # optional
# List if lines present in sshd_config
sshd_options: []

# Mounts
common_device_mounts: []
# Examle
# common_device_mounts:
#   - source: UUID=xyz | /dev/xyz
#     destination: /mnt/dst
#     filesystem: iso9660|xfs|ext4
#     options: ro,noauto

# System limets
common_limits: []
# Example
# common_limits:
#   - user: "*"
#     type: "hard"    # optional
#     limit: "nofile"
#     value: 1048576
#     comment: ""
#   - user: "docker"
#     type: "-"       # hard & soft
#     limit: "core"
#     value: 1048576
#     comment: ""     # optional

# Sets conf in /etc/network/interfaces
common_network_interfaces: []
# Example
# common_network_interfaces:
#   - interface: enp7s0
#     subnet: 10.10.1.1
#     address: 10.10.1.2
#     cloud_net: 10.10.0.0/16
#     netmask: 255.255.255.0    # Optional - default is 255.255.255.0
#     virtual_id: 4000          # Optional - for virtual devices (vSwitch)
#     mtu: 1400                 # Optional - default is 1400

# Key value pairs of hostname: ip
# Default is ansibe_host: ansible_ip
internal_hostnames: []
# Example
# internal_hostnames:
#   - name: waf-gateway
#     ips:
#       - '10.10.0.2'

# List of cron jobs
common_cron_jobs: []
# Example structure
# cron_jobs:
#   - name: Ping Google
#     job: ping google.de
#     weekday: '*'
#     month: '*'
#     minute: '*'
#     hour: '*'
#     day: '24'
#     state: present
#     user: null
