---
k8s_shared_api_server_endpoint: k8s-controlplane.local
# Time to life for the kubeadm bootstrap token. Default is never expire
k8s_autoscale_join_token_ttl: 0
k8s_autoscale_create_k8s_secret: true
k8s_autoscale_create_az_secret: false
k8s_pki_cert_path: /etc/kubernetes/pki

# VM images to use
k8s_hcloud_autoscale_img_arm64: name=debian-12-k8s-v1.33.0-arm64
k8s_hcloud_autoscale_img_amd64: name=debian-12-k8s-v1.33.0-amd64
k8s_hcloud_autoscale_conf_double_base64_encode: true

k8s_autoscale_user_data:
  #cloud-config
  write_files:
    - content: "{{ lookup('template', 'autoscale-join.sh.j2') }}"
      path: /srv/join-cluster.sh
      owner: root:root
      permissions: "0700"
  runcmd: "{{ k8s_etc_host_commands + ['/srv/join-cluster.sh']}}"

k8s_hcloud_autoscale_conf:
  imagesForArch:
    arm64: "{{ k8s_hcloud_autoscale_img_arm64 }}"
    amd64: "{{ k8s_hcloud_autoscale_img_amd64 }}"
  nodeConfigs:
    cas-arm-small:
      cloudInit: |
        #cloud-config
        {{ k8s_autoscale_user_data | to_nice_yaml }}
      labels:
        "node.kubernetes.io/role": "autoscaler-node"
    cas-amd-small:
      cloudInit: |
        #cloud-config
        {{ k8s_autoscale_user_data | to_nice_yaml }}
      labels:
        "node.kubernetes.io/role": "autoscaler-node"
