# Docs: https://kubernetes.io/docs/reference/access-authn-authz/authorization/
apiVersion: apiserver.config.k8s.io/v1
kind: AuthorizationConfiguration
authorizers:
  - type: Node
    name: node
  - type: RBAC
    name: rbac
