---
# k8s-monitoring-role-defaults

k8s_grafana_agent_logs_config_path: conf/grafana-log-config.yml.j2
k8s_grafana_agent_metrics_config_path: conf/grafana-metrics-config.yml.j2
k8s_grafana_agent_traces_config_path: conf/grafana-traces-config.yml.j2

k8s_grafana_agent_logs_install: true
k8s_grafana_agent_logs_agent_config: '{{ lookup("template", k8s_grafana_agent_logs_config_path) | from_yaml }}'
k8s_grafana_agent_logs_agent_app_path: apps/grafana-log-agent.yml.j2
k8s_grafana_agent_metrics_install: true
k8s_grafana_agent_metrics_agent_config: '{{ lookup("template", k8s_grafana_agent_metrics_config_path) | from_yaml }}'
k8s_grafana_agent_metrics_agent_app_path: apps/grafana-metrics-agent.yml.j2
k8s_grafana_agent_traces_install: true
k8s_grafana_agent_traces_agent_config: '{{ lookup("template", k8s_grafana_agent_traces_config_path) | from_yaml }}'
k8s_grafana_agent_traces_agent_app_path: apps/grafana-traces-agent.yml.j2
k8s_grafana_agent_traces_strategies_config:
  default_strategy:
    param: 0.001
    type: probabilistic

### Grafana-Agent ###
k8s_monitoring_install_grafana_agent: true
k8s_monitoring_prometheus_remote_write:
  - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
    # basic_auth:
    #   username: '{{ vault_k8s_monitoring_prometheus_user }}'
    #   password: '{{ vault_k8s_monitoring_prometheus_pw }}'
    # headers:
    #   X-Scope-OrgID: anonymous

k8s_monitoring_loki_remote_write:
  - url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
    # basic_auth:
    #   username: '{{ vault_k8s_monitoring_loki_user }}'
    #   password: '{{ vault_k8s_monitoring_loki_pw }}'
    # external_labels:
    #   cluster: '{{ inventory_dir | basename }}'

k8s_monitoring_tempo_remote_write:
  - endpoint: tempo-eu-west-0.grafana.net:443
    # basic_auth:
    #     username: '{{ vault_k8s_monitoring_tempo_pw }}'
    #     password: '{{ vault_k8s_monitoring_tempo_user }}'
    # retry_on_failure:
    #     enabled: false
