---
# k8s-monitoring-role-defaults

k8s_grafana_helm_repo: https://grafana.github.io/helm-charts
k8s_grafana_install: true
k8s_grafana_helm_chart_version: '{{ null | default(omit) }}'

# https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml
k8s_grafana_helm_values:
  cluster:
    name: '{{ k8s_cluster_name | default(inventory_dir | basename) }}'

  externalServices:
    prometheus:
      host: "https://prometheus-prod-01-eu-west-0.grafana.net"
    # basic_auth:
    #   username: '{{ vault_k8s_monitoring_prometheus_user }}'
    #   password: '{{ vault_k8s_monitoring_prometheus_pw }}'

    loki:
      host: "https://logs-prod-eu-west-0.grafana.net"
      # basicAuth:
      #   username: '{{ vault_k8s_monitoring_loki_user }}'
      #   password: '{{ vault_k8s_monitoring_loki_pw }}'

  opencost:
    opencost:
      prometheus:
        external:
          url: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom"