---
# Version of the chart to deploy
k8s_nginx_helm_chart_version: '{{ null | default(omit) }}'
k8s_nginx_install: true

# See: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
k8s_nginx_helm_values:
  controller:
    name: controller
    # -- Use a `DaemonSet` or `Deployment`
    kind: DaemonSet

# Service
    service:
      enabled: true
      # type: LoadBalancer
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
        tcp:
          8080: 32808

# Metrics
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/port: "10254"
          prometheus.io/scrape: "true"
