---
# Netlify-DNS

# See: https://open-api.netlify.com/
netlify_api_token: xxx
netlify_dns_zone_id: xxx

# List of dns records:
netlify_dns_records: []
# Example
# netlify_dns_records:
#  - { host: "my-domain.example", value: "127.0.0.1" }
#  - { host: "test.k8s.example.com", value: "127.0.0.1", type: A, ttl: 3600 }

# Internal dns query search
netlify_dns_compare_query: '[?hostname==`{{ item.host }}` && type==`{{ item.type | default("A") }}`]'
