# Main k8s/master/flannel Setup

- name: Download network CNI manifest
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    return_content: true
    status_code: [200, 304]
  register: _k8s_intanal_cni_flannel_definition
  run_once: true
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8-flannel]

- name: Apply flannel-cri manifest to the cluster
  kubernetes.core.k8s:
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    definition: "{{ _k8s_intanal_cni_flannel_definition.content }}"
    state: present
  run_once: true
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8-flannel]
