# Setup wasm crun
---
- name: Install kubelet and admin tools
  ansible.builtin.apt:
    name: 'containerd.io{{ "=" + k8s_containerd_version + "*" if (k8s_containerd_version != "latest") }}'
    state: present
    update_cache: true
    cache_valid_time: 86400 # equal to 24h
    install_recommends: false
    allow_downgrade: true
    autoremove: true
    allow_change_held_packages : true
  ignore_errors: '{{ ansible_check_mode }}'

- name: Test containerd
  ansible.builtin.command:
    cmd: containerd --version
  changed_when: false
