---
# Setup docker containerd
- name: k8s common - cri-o | Install cri-o
  ansible.builtin.apt:
    name: 'cri-o{{ "=" + k8s_crio_version + "*" if (k8s_crio_version != "latest") }}'
    state: present
    update_cache: true
    install_recommends: false
    allow_downgrade: true
    autoremove: true
    allow_change_held_packages: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: k8s common - cri-o | Test cri-o
  ansible.builtin.command:
    cmd: crio --version
  changed_when: false
  ignore_errors: "{{ ansible_check_mode }}"
