---
# Setup wasm crun
- name: k8s common - crun | Download crun
  ansible.builtin.unarchive:
    src: "{{ k8s_crun_wasm_download_url }}"
    dest: /tmp
    remote_src: true
    creates: /tmp/crun
  retries: 3

- name: k8s common - crun | Copy crun wasm files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0754"
    remote_src: true
  with_items:
    - src: /tmp/crun
      dest: /usr/local/bin/crun
    - src: "/tmp/wasmlibs/libwasmedge.so.{{ k8s_crun_wasmlib_version }}"
      dest: "/usr/wasmedge/lib/libwasmedge.so.{{ k8s_crun_wasmlib_version }}"

- name: k8s common - crun | Create symlink to wasm lib
  ansible.builtin.file:
    src: "/usr/wasmedge/lib/libwasmedge.so.{{ k8s_crun_wasmlib_version }}"
    dest: "/usr/wasmedge/lib/{{ item }}"
    state: link
  loop:
    [
      'libwasmedge.so.{{ k8s_crun_wasmlib_version | split(".") | first }}',
      "libwasmedge.so",
    ]

- name: k8s common - crun | Add wasm libs to server lib store
  ansible.builtin.lineinfile:
    path: /etc/ld.so.conf
    line: /usr/wasmedge/lib
  register: __was_lib_link_ad

- name: k8s common - crun | Reload lib link config
  when: __was_lib_link_ad.changed
  ansible.builtin.command:
    cmd: ldconfig

- name: k8s common - crun | Test crun
  ansible.builtin.command:
    cmd: crun --version
  changed_when: false
