---
# Setup crun
- name: k8s common - crun | Install official crun
  ansible.builtin.get_url:
    url: https://github.com/containers/crun/releases/download/{{ k8s_crun_version }}/crun-{{ k8s_crun_version }}-linux-{{ system_arch_map[ansible_facts.architecture] }}
    dest: /usr/local/sbin/crun
    owner: root
    group: root
    mode: "0754"

- name: k8s common - crun | Test crun
  ansible.builtin.command:
    cmd: crun --version
  changed_when: false
