---
# Setup firecracker containers
- name: k8s common - firecracker | Download firecracker
  ansible.builtin.unarchive:
    src: "{{ k8s_firecracker_download_url }}"
    dest: /opt/firecracker/
    list_files: true
    keep_newer: true
    extra_opts: ["--strip-components=1", "--show-stored-names"]
    exclude:
      - NOTICE
      - LICENSE
      - SHA256SUMS
      - THIRD-PARTY
      - "*.debug"
    remote_src: true
    creates: /opt/firecracker/firecracker
  register: __k8s_firecracker_res
  retries: 3

- name: k8s common - firecracker | Create symlink to binaries
  ansible.builtin.file:
    src: "/opt/firecracker/{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dst }}"
    state: link
  loop_control:
    label: "{{ item.dst }}"
  loop:
    - src: "firecracker-v{{ __firecracker_version }}-{{ ansible_facts.architecture }}"
      dst: firecracker
  vars:
    __firecracker_version: "{{ k8s_firecracker_download_url | regex_search('v([0-9.]+)') | regex_replace('^v', '') }}"

- name: k8s common - firecracker | Test firecracker
  ansible.builtin.command:
    cmd: firecracker --version
  changed_when: false
