---
# Setup kata containers
- name: k8s common - kata-containers | Download kata-containers
  ansible.builtin.unarchive:
    src: "{{ k8s_kata_containers_download_url }}"
    dest: /opt/kata/
    list_files: true
    keep_newer: true
    extra_opts: ["--strip-components=3", "--show-stored-names"]
    exclude: "{{ k8s_kata_containers_exclude_base }}"
    remote_src: true
    creates: /usr/local/bin/containerd-shim-kata-v2
  register: __k8s_kata_container_res
  retries: 3
  vars:
    k8s_kata_containers_exclude_base:
      - opt/kata/share/kata-containers/kata-ubuntu-noble-nvidia-gpu-590.48.01.image
      - opt/kata/share/kata-containers/kata-ubuntu-noble-nvidia-gpu-590.48.01.initrd
      - opt/kata/share/kata-containers/kata-ubuntu-noble-nvidia-gpu-confidential-590.48.01.image
      - opt/kata/share/kata-containers/kata-ubuntu-noble-nvidia-gpu-confidential-590.48.01.initrd
      - opt/kata/share/kata-containers/vmlinux-6.18.12-181-nvidia-gpu
      - opt/kata/share/kata-containers/vmlinuz-6.12.47-181-dragonball-experimental
      - opt/kata/share/kata-containers/vmlinux-6.12.47-181-dragonball-experimental
      - opt/kata/share/qemu-system-x86_64-snp-experimental
      - opt/kata/share/qemu-system-x86_64-tdx-experimental
      - opt/kata/bin/qemu-system-x86_64-snp-experimental
      - opt/kata/bin/qemu-system-x86_64-tdx-experimental
      - opt/kata/versions.yaml

- name: k8s common - kata-containers | Create symlink to binaries
  when: item.when | default(true)
  ansible.builtin.file:
    src: "{{ item.binary }}"
    dest: "{{ item.prefix | default('/usr/local/bin/') }}{{ item.binary | split('/') | last }}"
    state: link
    owner: root
  loop:
    - binary: /opt/kata/bin/qemu-system-x86_64
    - binary: /opt/kata/bin/kata-monitor
    - binary: /opt/kata/bin/jailer
    - binary: /opt/kata/bin/kata-runtime
    - binary: /opt/kata/bin/cloud-hypervisor
    - binary: >-
        {{ '/opt/kata/runtime-rs/bin'
        if k8s_kata_containers_use_rust_rs
        else '/opt/kata/bin'
        }}/containerd-shim-kata-v2
    - binary: /opt/kata/bin/firecracker
      when: "{{ k8s_kata_containers_use_packaged_firecracker }}"
    - binary: /opt/kata/share/defaults/kata-containers/runtime-rs/configuration.toml
      prefix: /etc/kata-containers/runtime-rs/
  loop_control:
    label: "{{ item.binary }}"

- name: k8s common - kata-containers | Add manager and shim alias
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.dst }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  loop_control:
    label: "{{ item.dst }}"
  vars:
    __kata_runtime_conf:
      fc: >-
        /opt/kata/share/defaults/kata-containers/
        {{ "runtime-rs/configuration-rs-fc.toml"
        if k8s_kata_containers_use_rust_rs
        else "configuration-fc.toml"
        }}
      qemu: >-
        /opt/kata/share/defaults/kata-containers/
        {{ "runtime-rs/configuration-qemu-runtime-rs.toml"
        if k8s_kata_containers_use_rust_rs
        else "configuration-qemu.toml"
        }}
      clh: >-
        /opt/kata/share/defaults/kata-containers/
        {{ "runtime-rs/configuration-cloud-hypervisor.toml"
        if k8s_kata_containers_use_rust_rs
        else "configuration-clh.toml"
        }}
  with_items:
    - content: >-
        {{
        lookup("ansible.builtin.url",
        "https://raw.githubusercontent.com/kata-containers/kata-containers/refs/heads/main/utils/kata-manager.sh",
        split_lines=false)
        }}
      dst: /usr/local/bin/kata-manager
      mode: "0744"
    - content: |
        #!/bin/bash
        # Specify the configuration file and pass all arguments to the shim binary
        KATA_CONF_FILE={{ __kata_runtime_conf.fc | regex_replace("\s","") }} /usr/local/bin/containerd-shim-kata-v2 $@
      dst: /usr/local/bin/containerd-shim-kata-fc-v2
      mode: "0744"
    - content: |
        #!/bin/bash
        # Specify the configuration file and pass all arguments to the shim binary
        KATA_CONF_FILE={{ __kata_runtime_conf.clh | regex_replace("\s","") }} /usr/local/bin/containerd-shim-kata-v2 $@
      dst: /usr/local/bin/containerd-shim-kata-clh-v2
      mode: "0744"
    - content: |
        #!/bin/bash
        # Specify the configuration file and pass all arguments to the shim binary
        KATA_CONF_FILE={{ __kata_runtime_conf.qemu | regex_replace("\s","") }} /usr/local/bin/containerd-shim-kata-v2 $@
      dst: /usr/local/bin/containerd-shim-kata-qemu-v2
      mode: "0744"

- name: k8s common - kata-containers | Ensure kata runtime conf's exist
  ansible.builtin.command:
    cmd: "kata-manager -S {{ item }}"
    creates: /etc/kata-containers/configuration-{{ item }}.toml
  changed_when: false
  loop: [clh, fc, qemu]

- name: k8s common - kata-containers | Test kata-containers
  ansible.builtin.command:
    cmd: kata-runtime check
  changed_when: false
