---
# Setup kubelet-credential-provider
- name: k8s common - kubelet-credential-provider | Ensure binary dir exists
  ansible.builtin.file:
    path: "{{ k8s_credential_provider_bin_dir }}"
    state: directory

- name: k8s common - kubelet-credential-provider | Install ecr-credential-provider
  ansible.builtin.unarchive:
    src: "{{ k8s_credential_provider_ecr_download_url }}"
    dest: "{{ k8s_credential_provider_bin_dir }}"
    creates: "{{ k8s_credential_provider_bin_dir }}ecr-credential-provider"
    exclude: [LICENSE, README.md]
    remote_src: true
  retries: 3

- name: k8s common - kubelet-credential-provider | Copy credential-provider config
  no_log: true
  ansible.builtin.template:
    src: kubelet-credential-conf.yml.j2
    dest: "{{ k8s_credential_provider_config_dest }}"
    mode: "0644"
    owner: root
    group: root
    validate: yq . %s

- name: k8s common - kubelet-credential-provider | Test credential-provider
  ansible.builtin.shell:
    cmd: "{{ k8s_credential_provider_bin_dir }}ecr-credential-provider --help"
  changed_when: false
