---
# Setup spin
- name: k8s common - spin | Install spin
  ansible.builtin.unarchive:
    src: "{{ k8s_spin_download_url }}"
    dest: /usr/local/bin
    list_files: true
    remote_src: true
    mode: 0755
    exclude:
      - README.md
      - LICENSE
    creates: /usr/local/bin/containerd-shim-spin-v2
  register: __k8s_spin_download
  retries: 3

- name: k8s common - spin | Test spin
  ansible.builtin.command:
    cmd: containerd-shim-spin-v2 -v
  changed_when: false
