# Setup stargz
- name: k8s common - stargz | Install stargz
  ansible.builtin.unarchive:
    src: "{{ k8s_stargz_download_url }}"
    dest: /usr/local/bin
    list_files: true
    remote_src: true
    mode: 0755
    exclude:
      - stargz-store
      - stargz-store-helper
      - ctr-remote
    creates: /usr/local/bin/containerd-stargz-grpc
  retries: 3

- name: k8s common - stargz | Copy stargz system service
  ansible.builtin.get_url:
    dest: /etc/systemd/system/stargz-snapshotter.service
    url: https://raw.githubusercontent.com/containerd/stargz-snapshotter/main/script/config/etc/systemd/system/stargz-snapshotter.service
    mode: "0600"
  retries: 3

- name: k8s common - stargz | Enable stargz service
  ansible.builtin.systemd:
    name: stargz-snapshotter.service
    state: started
    daemon_reload: true
    enabled: true

- name: k8s common - stargz | Check stargz
  ansible.builtin.command:
    cmd: containerd-stargz-grpc -version
  changed_when: false
