# Install gvisor
---
- name: gVisor repository
  ansible.builtin.deb822_repository:
    name: gvisor
    types: [deb]
    uris: https://storage.googleapis.com/gvisor/releases
    signed_by: https://gvisor.dev/archive.key
    components: [main]
    suites: [release]
    state: present
    enabled: True
  tags: [docker, docker-install]

- name: Install gVisor
  ansible.builtin.apt:
    state: present
    install_recommends: false
    name: runsc
  tags: [docker, docker-install]
