# Main Traefik Setup
---
- name: Add traefik user
  user:
    name: traefik
    comment: User for traefik server
    group: adm
    ansible.builtin.shell: /usr/sbin/nologin
    create_home: false
    system: true
    state: present
  tags: [ingress, traefik]

- name: Check if traefik is setup
  ansible.builtin.command: "which traefik"
  register: traefik_check_result
  changed_when: false
  failed_when: false
  tags: [ingress, traefik]

- name: Get traefik URL
  ansible.builtin.shell: |
    curl --silent https://api.github.com/repos/traefik/traefik/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep linux_amd64.tar.gz
  changed_when: false
  register: traefik_url
  tags: [ingress, traefik]

- name: Download and unzip traefik
  when: traefik_check_result.stdout == "" or traefik_force_reinstall
  ansible.builtin.unarchive:
    src: '{{ traefik_url.stdout }}'
    dest: /tmp
    remote_src: true
  tags: [ingress, traefik]

- name: Give insecure permissions to an existing file
  when: traefik_check_result.stdout == "" or traefik_force_reinstall
  ansible.builtin.file:
    path: /tmp/traefik
    owner: traefik
    group: adm
    mode: '0750'

- name: Install traefik
  when: traefik_check_result.stdout == "" or traefik_force_reinstall
  ansible.builtin.shell: |
    mv /tmp/traefik /usr/local/bin/traefik
  notify: Restart traefik
  tags: [ingress, traefik]

- name: Test traefik
  ansible.builtin.command: "traefik version"
  changed_when: false
  tags: [ingress, traefik]

- name: Copy traefik service config
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart traefik
  tags: [ingress, traefik]

- name: Ensue config folder exists
  ansible.builtin.file:
    path: /srv/traefik
    state: directory
  tags: [ingress, traefik]

- name: Ensue log folder exists
  ansible.builtin.file:
    path: /var/log/traefik
    recurse: true
    state: directory
    owner: traefik
    group: adm
    mode: '0644'
  tags: [ingress, traefik]

- name: Copy Traefik default config
  ansible.builtin.copy:
    src:  traefik
    dest: /srv/traefik
    owner: traefik
    group: adm
    mode: '0666'
  notify: Restart traefik
  tags: [ingress, traefik]
