---
##### ingress #####

ingress_proxy: '{{ ingress_default_proxy }}'
ingress_default_proxy: nginx


ingress_conf:
  conf:
    nginx:
      common_header: |
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
      common_server_settings: ''
########################################################################
# NOTE: nginx
# The upsteams are always named after the host with the suffix of the defined upstream route
# Resulting in <HOSTNAME>_<UPSTREAM_ROUTE>. To pass use proxy_pass http://<HOSTNAME><UPSTREAM_ROUTE>/;
# Example Host: example.com; upstream: example.com_default
# If flase location is given a default location ("/") is created. It will proxy pass to <HOSTNAME>_default.
# Every location contains the common headers and the proxypass to the defined upstream ips
########################################################################
# NOTE: traefik
    traefik:
      middlewares:
        auth:
          basicAuth:
            users:
              - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
        testHeader:
          headers:
            customResponseHeaders:
              X-Custom-Response-Header: "value"
############################## sites-nginx #####################################
  sites:
    - host: default.devops-testing.123preview.com
      ip: 116.202.189.62
      upstreams:
        - 10.10.0.2:8001
      # tls:
      #   crt: /etc/letsencrypt/dummy/fullchain.pem
      #   key: /etc/letsencrypt/dummy/privkey.pem
    - host: whoami.devops-testing.123preview.com
      ip: 116.202.189.62
      upstreams:
        - 10.10.0.2:8003
    - host: custom.devops-testing.123preview.com
      ip: 116.202.189.62
      upstreams:
        - 10.10.0.2:8002
        - 10.10.0.2:8002
      nginx:
        locations:
          - route: /
            body: |
              proxy_pass http://custom.devops-testing.123preview.com_default;
          - route: /test
            body: |
              return 404;
        server_settings: ''
############################## sites-traefik #####################################
    - host: default.work.example.com
      ip: 162.55.216.225
      upstreams:
        - 10.10.0.4:8001
    - host: whoami.work.example.com
      upstreams:
        - 10.10.0.4:8003
      traefik:
        protocol: http
        middlewares: [auth, testHeader]
    - host: custom.work.example.com
      upstreams:
        - 10.10.0.4:22
        - 10.10.0.4:22
      tls: false
      traefik:
        protocol: tcp
