---
k8s_version: 1.25.5
k8s_cluster_name: '{{ inventory_dir | basename }}'
k8s_image_repo: registry.k8s.io
k8s_shared_api_server_endpoint: '{{ ansible_facts.default_ipv4.address }}'
k8s_pod_network_cidr: 10.244.0.0/16
k8s_cert_extra_sans: '{{ ["127.0.0.1"] + ansible_facts.all_ipv4_addresses }}'
k8s_install_k9s: true

k8s_kubeadm_opts: ''
k8s_init_opts: ''
k8_cert_key: none

k8s_remove_no_schedule_cp_taints: false

# Taints
k8s_taints: []
# # Example
# k8s_taints:
#   - node: '{{ ansible_facts.hostname }}'
#     key: node-role.kubernetes.io/control-plane
#     effect: NoSchedule
#     state: absent

######### CNI #########
# Which CNI flannel, calico or cilium
k8s_cni: flannel
# Helm chart version
k8s_calico_chart_version: '{{ null | default(omit) }}'
k8s_cilium_chart_version: '{{ null | default(omit) }}'
# Helm chart values
k8s_cilium_helm_values:
  # -- Configure the underlying network MTU to overwrite auto-detected MTU.
  MTU: 1450 # for Hetzner
  # Recreate agent on config map change
  rollOutCiliumPods: true
  # bgp:
  #   # -- Enable BGP support inside Cilium; embeds a new ConfigMap for BGP inside
  #   # cilium-agent and cilium-operator
  #   enabled: false
  #   announce:
  #     # -- Enable allocation and announcement of service LoadBalancer IPs
  #     loadbalancerIP: false
  #     # -- Enable announcement of node pod CIDR
  #     podCIDR: false

  # -- Configure the encapsulation configuration for communication between nodes.
  # Possible values:
  #   - disabled
  #   - vxlan (default)
  #   - geneve
  tunnel: "vxlan"

k8s_calico_helm_values:
# See https://docs.tigera.io/calico/3.25/getting-started/kubernetes/helm
  installation:
    cni:
      type: Calico
    calicoNetwork:
      ipPools:
        - cidr: '{{ k8s_pod_network_cidr }}'
