---
k8s_version: 1.25.5
k8s_cluster_name: '{{ inventory_dir | basename }}'
k8s_image_repo: registry.k8s.io
k8s_shared_api_server_endpoint: '{{ ansible_facts.default_ipv4.address }}'
k8s_init_verbose: '{{ lookup("env", "CI") | default("false", True) | bool == True }}'
k8s_pod_network_cidr: 10.244.0.0/16
k8s_cert_extra_sans: '{{ ["127.0.0.1"] + ansible_facts.all_ipv4_addresses }}'
k8s_install_k9s: true

k8s_kubeadm_opts: ''
k8s_init_opts: ''
k8_cert_key: none

k8s_remove_no_schedule_cp_taints: false

# Taints
k8s_taints: []
# # Example
# k8s_taints:
#   - node: '{{ ansible_facts.hostname }}'
#     key: node-role.kubernetes.io/control-plane
#     effect: NoSchedule
#     state: absent

######### CNI #########
# Which CNI flannel, calico or cilium
k8s_cni: flannel

# Calico helm chart setup
k8s_calico_chart_version: '{{ null | default(omit) }}'
k8s_calico_helm_values:
# See https://docs.tigera.io/calico/3.25/getting-started/kubernetes/helm
  installation:
    cni:
      type: Calico
    calicoNetwork:
      ipPools:
        - cidr: '{{ k8s_pod_network_cidr }}'

# Cilium helm chart setup
k8s_cilium_chart_version: '{{ null | default(omit) }}'
# See example setup: https://github.com/syself/cluster-api-provider-hetzner/blob/main/templates/cluster-templates/bases/hcloud-kcp-ubuntu.yaml#L136
k8s_cilium_helm_values:
  rollOutCiliumPods: true
  priorityClassName: "system-node-critical"

  hubble:
    metrics:
      enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
    relay:
      enabled: true
      rollOutPods: true
    ui:
      enabled: true
      rollOutPods: true
  ipam:
    mode: "kubernetes"

  kubeProxyReplacement: "partial"

  operator:
    rollOutPods: true
    priorityClassName: "system-node-critical"

  # encryption:
  #   enabled: true
  #   type: wireguard
  # # -- Configure the underlying network MTU to overwrite auto-detected MTU.
  # MTU: 1450 # for Hetzner
  # # Recreate agent on config map change
  # tunnel: "vxlan"
