# K8s install generic helm apps

- name: Deploying custom apps
  kubernetes.core.k8s:
    namespace: '{{ k8s_app.namespace | default(omit) }}'
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: '{{ k8s_app.state | default("present") }}'
    definition: '{{ lookup("template", k8s_app.file) | from_yaml_all }}'
    wait: '{{ k8s_app.wait | default(true) }}'
  loop: '{{ k8s_app_manifests | default([]) }}'
  loop_control:
    loop_var: k8s_app
    label: '{{ k8s_app.name }}'
  tags: [k8s, k8s-deploy, k8s-deploy-manifest]

- name: Install Helm App
  ansible.builtin.include_tasks: helm-deploy.yml
  loop: '{{ k8s_app_helm_apps | default([]) }}'
  loop_control:
    loop_var: k8s_helm_app
    label: '{{ k8s_helm_app.chart_name }}'
  tags: [k8s, k8s-deploy, helm-deploy]
