- name: Ensue user is created
  ansible.builtin.user:
    name: "{{ gitlab_runner_rootless_user }}"
    groups: ["{{ gitlab_runner_rootless_user }}"]
    append: true
    create_home: true
    state: present
  register: __glab_runner_user
  tags: [gitlab-runner, gitlab-runner-rootless]

- name: Write gitlab-runner-conf file
  ansible.builtin.template:
    src: gitlab-runner.conf.j2
    dest: "/home/{{ gitlab_runner_rootless_user }}/gitlab-runner-config.toml"
    owner: "{{ gitlab_runner_rootless_user }}"
    group: "{{ gitlab_runner_rootless_user }}"
    mode: "0640"
  register: __glab_runner_conf
  tags: [gitlab-runner, gitlab-runner-rootless]

- name: Write gitlab-runner-env file
  ansible.builtin.copy:
    content: "DOCKER_HOST=unix:///run/user/{{ __glab_runner_user.uid }}/docker.sock"
    dest: "/home/{{ gitlab_runner_rootless_user }}/runner.env"
    mode: "0640"
  tags: [gitlab-runner, gitlab-runner-rootless]

- name: Start rootless docker
  become: true
  become_user: "{{ gitlab_runner_rootless_user }}"
  ansible.builtin.shell: dockerd-rootless-setuptool.sh install
  args:
    chdir: "/home/{{ gitlab_runner_rootless_user }}"
    creates: "/run/user/{{ __glab_runner_user.uid }}/docker.sock"
  tags: [gitlab-runner, gitlab-runner-rootless]

# - name: Enable and start gitlab-runner service
#   become: true
#   become_user: "{{ gitlab_runner_rootless_user }}"
#   # environment:
#   #   XDG_RUNTIME_DIR: "/run/user/{{ demo_user_info.ansible_facts.getent_passwd.demo.1 }}"
#   shell: |
#     systemctl --user daemon-reload
#     systemctl --user enable gitlab-runner
#     systemctl --user start gitlab-runner
# tags: [gitlab-runner, gitlab-runner-rootless]

- name: Enable and start gitlab-runner service
  ansible.builtin.systemd_service:
    name: gitlab-runner
    enabled: true
    state: started
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __glab_runner_user.uid }}"
  tags: [gitlab-runner, gitlab-runner-rootless]

- name: Log into Docker registries
  community.docker.docker_login:
    registry_url: '{{ item.registry | default("https://index.docker.io/v1/") }}'
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    reauthorize: true
  loop: "{{ gitlab_runner_docker_registries }}"
  loop_control:
    label: '{{ item.registry | default("https://index.docker.io/v1/") }}'
  tags: [gitlab-runner, gitlab-runner-docker-install]
