---
# Set up k8s with kubeadm
- name: k8s cp - kubeadm | Init first control-plane node
  block:
    - name: k8s common | Pre-pull images
      ansible.builtin.command: |
        kubeadm config images pull \
          {{ "--kubernetes-version " + k8s_version if (k8s_version != "latest") }} \
          {{ "--image-repository " + k8s_image_repo if (k8s_image_repo | default("") != "") }}
      register: __k8s_pull_res
      changed_when: >-
        ((__k8s_pull_res.end[:-7]
        | to_datetime) - (__k8s_pull_res.start[:-7]
        | to_datetime)).total_seconds() > 5
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Reset Kubernetes components
      ansible.builtin.command: "kubeadm reset --force"
      register: reset_cluster
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Init Kubernetes cluster
      when: reset_cluster is succeeded
      ansible.builtin.command: |
        kubeadm init \
          --config {{ target_data_dir | default("") }}/srv/kubeadm-config.yaml \
          --upload-certs
      register: init_cluster
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Enable and check kubelet service
      ansible.builtin.systemd:
        name: kubelet
        daemon_reload: true
        state: started
        enabled: true
      ignore_errors: "{{ ansible_check_mode }}"
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Debug - Kubeadm init res
      when: k8s_init_verbose
      ansible.builtin.debug:
        var: init_cluster.stderr_lines + init_cluster.stdout_lines
      tags: [k8s, k8s-init, k8s-cp-init]

  rescue:
    - name: k8s cp - kubeadm | Cleanup - Reset Kubernetes component
      ansible.builtin.command: "kubeadm reset --force"
      changed_when: true
      register: reset_cluster
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Print Error Info
      ansible.builtin.debug:
        msg: |
          A error occurred while bootstrapping the first control-plane node.
          The cluster was reset. Please see the error message below:"
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Kubeadm Error
      ansible.builtin.debug:
        var: init_cluster
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Exit with error code!
      ansible.builtin.command: /bin/false
      tags: [k8s, k8s-init, k8s-cp-init]
