---
# Set up k8s with kubeadm
- name: k8s cp - kubeadm | Init first control-plane node
  block:
    - name: k8s cp - kubeadm | Init Kubernetes cluster
      ansible.builtin.command: |
        kubeadm init \
          --config {{ target_data_dir | default("") }}/srv/kubeadm-config.yaml \
          --upload-certs
      register: init_cluster
      timeout: 300
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Debug - Kubeadm init res
      when: k8s_init_verbose
      ansible.builtin.debug:
        var: init_cluster.stderr_lines + init_cluster.stdout_lines
      tags: [k8s, k8s-init, k8s-cp-init]

  rescue:
    - name: k8s cp - kubeadm | Cleanup - Reset Kubernetes component
      ansible.builtin.command: "kubeadm reset --force"
      changed_when: true
      register: reset_cluster
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Kubeadm Error
      ansible.builtin.debug:
        var: init_cluster
      tags: [k8s, k8s-init, k8s-cp-init]

    - name: k8s cp - kubeadm | Print Error Info
      ansible.builtin.fail:
        msg: |
          A error occurred while bootstrapping the first control-plane node.
          The cluster was reset. Please see the error message above:"
      tags: [k8s, k8s-init, k8s-cp-init]
