# Main k8s Setup
---
- name: Include common vars
  ansible.builtin.include_vars:
    file: ../../common_vars.yml
    name: common_vars
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Test reachability to shared KubeControlPlaneHost
  ansible.builtin.command: 'ping -c 5 {{ k8s_shared_api_server_endpoint }}'
  changed_when: false
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Assert that k8s_etcd_encryption_secret has the right length
  ansible.builtin.assert:
    that: [k8s_etcd_encryption_secret | length == 32]
    fail_msg: "'k8s_etcd_encryption_secret' must be 32 characters long"
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Copy etcd encryption config
  ansible.builtin.template:
    src: encryption-config.yaml.j2
    dest: /etc/kubernetes/enc/encryption-config.yaml
    mode: '0600'
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Check if kubeadm has already run
  when: groups.k8s_control_plane | flatten | first == inventory_hostname
  ansible.builtin.stat:
    path: "{{ k8s_pki_cert_path }}"
  register: kubeadm_ca
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Init cluster if needed
  when: groups.k8s_control_plane | flatten | first == inventory_hostname and not kubeadm_ca.stat.exists
  ansible.builtin.include_tasks: kubeadm-init.yml
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Generate certificate key
  delegate_to: '{{ groups.k8s_control_plane | flatten | first }}'
  ansible.builtin.command: 'kubeadm init phase upload-certs --upload-certs --config {{ target_data_dir | default("") }}/srv/kubeadm-config.yml'
  register: __k8s_kubeadm_cert_key_res
  changed_when: false
  run_once: true
  no_log: true
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Get join token
  delegate_to: '{{ groups.k8s_control_plane | flatten | first }}'
  ansible.builtin.command: kubeadm token create
  register: __k8_cp_join_token_res
  changed_when: false
  run_once: true
  no_log: true
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Get CA certificate hash
  delegate_to: '{{ groups.k8s_control_plane | flatten | first }}'
  community.crypto.x509_certificate_info:
    path: '{{ k8s_pki_cert_path }}/ca.crt'
  register: __k8s_pki_ca
  changed_when: false
  run_once: true
  no_log: true
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Copy kubeadm join config
  ansible.builtin.template:
    src: 'kubeadm-join-config.yml.j2'
    dest: '{{ target_data_dir | default("") }}/srv/kubeadm-join-config.yml'
    mode: '0600'
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Check if kubeadm has already run
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: k8s_kubeadm_all_init
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Join control-plane nodes
  when: not k8s_kubeadm_all_init.stat.exists
  ansible.builtin.command: |
    kubeadm join -v 5 --config {{ target_data_dir | default("") }}/srv/kubeadm-join-config.yml
  register: __k8s_join_res
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Change kubelet conf permissions
  ansible.builtin.file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: '0600'
  loop: [/var/lib/kubelet/config.yaml, /lib/systemd/system/kubelet.service ]
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Enable and check kubelet service
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: true
    state: started
    enabled: true
  ignore_errors: '{{ ansible_check_mode }}'
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Show join results
  when: k8s_init_verbose
  ansible.builtin.debug:
    var: __k8s_join_res
  tags: [k8s, k8s-init, k8s-cp-init]

- name: Remove NoSchedule taint form control-plane nodes
  when: k8s_remove_no_schedule_cp_taints
  kubernetes.core.k8s_taint:
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: absent
    name: '{{ ansible_facts.hostname }}'
    taints:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node.cloudprovider.kubernetes.io/uninitialized
        effect: NoSchedule
      - key: dedicated
  tags: [k8s, k8s-init, k8s-cp-init, k8s-taint]

- name: Setting taints
  kubernetes.core.k8s_taint:
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: '{{ item.state | default("present") }}'
    name: '{{ item.node }}'
    taints:
      - key: '{{ item.key }}'
        effect: '{{ item.effect | default(omit) }}'
  loop: '{{ k8s_taints | default([]) }}'
  tags: [k8s, k8s-init, k8s-cp-init, k8s-taint]

- name: Deploying initial resource manifests
  kubernetes.core.k8s:
    namespace: '{{ k8s_init_resources.namespace | default(omit) }}'
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: '{{ k8s_init_resources.state | default("present") }}'
    definition: '{{ k8s_init_resources.definition }}'
    wait: '{{ k8s_init_resources.wait | default(true) }}'
  loop: '{{ k8s_init_resources_manifests_all | flatten }}'
  loop_control:
    loop_var: k8s_init_resources
    label: '{{ k8s_init_resources.name }}'
  vars:
    k8s_init_resources_manifests_all:
      - '{{ k8s_init_resources_manifests }}'
      - '{{ [k8s_crun_manifest] }}'
      - '{{ [k8s_gVisor_manifest] if(k8s_install_gvisor) else [] }}'
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cp-init-maifests]

- name: Setup configs
  ansible.builtin.include_tasks: setup-configs.yml
  tags: [k8s, k8s-init, k8s-cp-init, k8s-init-config]

- name: Install Helm
  ansible.builtin.include_role:
    name: k8s/helm
    public: true
  tags: [k8s, k8s-init, k8s-cp-init, k8s-helm]

- name: Setup k9s
  when: k8s_install_k9s
  ansible.builtin.include_tasks: 'setup-k9s.yml'
  tags: [k8s, k8s-init, k8s-cp-init, k8s-k9s]

- name: Setup CNI
  ansible.builtin.include_tasks: 'setup-cni-{{ k8s_cni | lower }}.yml'
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cni, k8s-flannel, k8s-calico, k8s-cilium, k8s-weave]

# - name: Kubeadm check
#   ansible.builtin.shell: kubectl cluster-info
#   register: k8s_cluster_info
#   tags: [k8s, k8s-init, k8s-cp-init]

# - name: Debug - Print cluster info
#   ansible.builtin.debug:
#     var: k8s_cluster_info.stderr_lines + k8s_cluster_info.stdout_lines
#   run_once: true
#   tags: [k8s, k8s-init, k8s-cp-init]
