---
# Main k8s CNI - Cilium
- name: k8s cp - cni cilium | Add Cilium helm chart repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cni, k8s-cilium]

- name: k8s cp - cni cilium | Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ k8s_cilium_chart_version }}"
    release_namespace: kube-system
    update_repo_cache: true
    create_namespace: true
    state: present
    atomic: true
    wait: true
    timeout: 2m
    values: "{{ k8s_cilium_helm_values | default({}) }}"
    kubeconfig: "{{ k8s_kubeconfig }}"
  run_once: true
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cni, k8s-cilium]

- name: k8s cp - cni cilium | Download Cilium CLI
  ansible.builtin.unarchive:
    src: "https://github.com/cilium/cilium-cli/releases/download/{{ k8s_cilium_cli_version | default(lookup('url', 'https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt', split_lines=False)) | trim }}/cilium-linux-{{ system_arch_map[ansible_facts.architecture] }}.tar.gz"
    dest: /usr/local/bin
    creates: /usr/local/bin/cilium
    remote_src: true
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cni, k8s-cilium]

- name: k8s cp - cni cilium | Verify Cilium
  ansible.builtin.command: cilium status --output json
  register: __k8s_cilium_status
  changed_when: false
  run_once: true
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cni, k8s-cilium]
