---
# Main k8s CNI - flannel
- name: k8s cp - cni flannel | Download network CNI manifest
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    return_content: true
    status_code: [200, 304]
  register: _k8s_intanal_cni_flannel_definition
  run_once: true
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cni, k8-flannel]

- name: k8s cp - cni flannel | Apply flannel-cri manifest to the cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ _k8s_intanal_cni_flannel_definition.content }}"
    state: present
  run_once: true
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cni, k8-flannel]
