---
# k9s Setup
- name: k8s cp - k9s | Install k9s
  ansible.builtin.unarchive:
    src: >-
      {{
      lookup("url", "https://api.github.com/repos/derailed/k9s/releases/latest")
      | from_json
      | community.general.json_query(__k9s_url_query)
      | first
      }}
    dest: /usr/local/bin
    remote_src: true
    mode: "0755"
    creates: /usr/local/bin/k9s
    exclude: [README.md, LICENSE]
  vars:
    __k9s_url_query: "assets[?contains(name,'Linux_{{ system_arch_map[ansible_facts.architecture] }}')].browser_download_url"
