# Main k8s Setup
- name: Download network CNI manifest
  ansible.builtin.get_url:
    url: https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
    dest: ~/cri-weave.yml
    mode: '0664'
  run_once: true
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cni, k8-weave]

- name: Apply weave-cri manifest to the cluster
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    src: ~/cri-weave.yml
  run_once: true
  tags: [k8s, k8s-init, k8s-cp-init, k8s-cni, k8-weave]
