# Main k8s MetalLB setup

- name: Add MetalLB Helm-chart repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb
  tags: [k8s, k8s-init, k8-loadbalancer, k8-metallb]

- name: Deploy MetalLB
  kubernetes.core.helm:
    name: metallb
    state: '{{ "present" if(k8s_metallb_install) else "absent" }}'
    chart_ref: metallb/metallb
    chart_version: "{{ k8s_metallb_chart_version }}"
    release_namespace: metallb-system
    create_namespace: true
    update_repo_cache: true
    atomic: true
    wait: true
    values: "{{ k8s_metallb_helm_values | default({}) }}"
    kubeconfig: "{{ k8s_kubeconfig | default('/etc/kubernetes/admin.conf') }}"
  tags: [k8s, k8s-init, k8-loadbalancer, k8-metallb]

- name: Checking MetalLB IP-Pool
  ansible.builtin.debug:
    msg: '{{ "Will deploy IP Pool" + k8s_metallb_addresses | to_yaml + "to MetalLB" if (k8s_metallb_addresses | length != 0) else "No IP-Pool given. Aborting" }}'
  failed_when: k8s_metallb_addresses | length == 0
  tags: [k8s, k8s-init, k8-loadbalancer, k8-metallb]

- name: Apply MetalLB IP Pool
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig | default('/etc/kubernetes/admin.conf') }}"
    state: '{{ "present" if(k8s_metallb_install) else "absent" }}'
    wait: true
    template: metallb-address-pool.yml.j2
  tags: [k8s, k8s-init, k8-loadbalancer, k8-metallb]
