# Main k8s Rancher setup

- name: Add MetalLB Helm-Chart repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb
  tags: [k8s, k8-init, k8-loadbalancer, k8-metallb]

- name: Deploy MetalLB
  kubernetes.core.helm:
    name: metallb
    state: '{{ "present" if(k8s_metallb_install) else "absent" }}'
    chart_ref: metallb/metallb
    chart_version: '{{ k8s_metallb_chart_version }}'
    release_namespace: metallb-system
    create_namespace: true
    update_repo_cache: true
    atomic: true
    wait: true
    values: '{{ k8s_metallb_helm_values | default({}) }}'
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
  tags: [k8s, k8-init, k8-loadbalancer, k8-metallb]

- name: Checking MetalLB conf dir
  ansible.builtin.file:
    path: '{{ target_data_dir | default("") }}/srv/metallb'
    state: directory
  tags: [k8s, k8-init, k8-loadbalancer, k8-metallb]

- name: Checking MetalLB IP-Pool
  ansible.builtin.debug:
    msg: '{{ "Will deploy IP Pool" + k8s_metallb_addresses | to_yaml + "to MetalLB" if (k8s_metallb_addresses | length != 0) else "No IP-Pool given. Aborting" }}'
  failed_when: k8s_metallb_addresses | length == 0
  tags: [k8s, k8-init, k8-loadbalancer, k8-metallb]

- name: Creating IP-Pool File
  ansible.builtin.template:
    src: metallb-address-pool.yml.j2
    dest: '{{ target_data_dir | default("") }}/srv/metallb/metallb-address-pool.yml'
    mode: '0644'
  tags: [k8s, k8-init, k8-loadbalancer, k8-metallb]

- name: Apply MetalLB IP Pool
  kubernetes.core.k8s:
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: present
    src: '{{ target_data_dir | default("") }}/srv/metallb/metallb-address-pool.yml'
  tags: [k8s, k8-init, k8-loadbalancer, k8-metallb]
